version: 2.0.0.{build}
os: Visual Studio 2015
configuration: Release
platform: Any CPU
environment:
  NSIS_ROOT: 'C:\Program Files (x86)\NSIS'
install:
  - choco install nsis -pre -y
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-$(APPVEYOR_REPO_COMMIT)'
before_build:
- ps: nuget restore
build:
  project: Tabster.sln
after_build:
  - '"%NSIS_ROOT%\makensis.exe" /DAPPLICATION_VERSION="{version}" /DSOLUTION_DIRECTORY="(APPVEYOR_REPO_COMMIT)" "Build\Tabster.nsi"'