version: 2.0.0.{build}
os: Visual Studio 2015
configuration: Release
platform: Any CPU
install:
  - choco install nsis -pre -y
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-$(APPVEYOR_REPO_COMMIT)'
before_build:
- ps: nuget restore
build:
  project: Tabster.sln
after_build:
- ps: >-
    .\Deploy\Installer\nsis.ps1
- ps: >-
    .\Deploy\Portable\portable.ps1
artifacts:
- path: 'Tabster $(APPVEYOR_BUILD_VERSION) Setup.exe'
  name: installer
- path: 'Tabster $(APPVEYOR_BUILD_VERSION) Portable.exe'
  name: portable