version: 2.0.0.{build}
os: Visual Studio 2015
configuration: Release
platform: Any CPU
environment:
  sign_tool: C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\Bin\signtool.exe
  cert_pass:
    secure: G5EnVSbVc5p3Y4RHX1b1IHmMLMD8GRMYnZ3EwMr9odI=
  cert_secret:
    secure: i8AiTofAQPQgIuZiNpm47nqiHmpzp7afgUgvDurFf+Y=
install:
  - choco install nsis -y --ignore-checksums
  - nuget install secure-file -ExcludeVersion
  - secure-file\tools\secure-file -decrypt C:\projects\tabster\deploy\tabster.pfx.enc -secret %cert_secret%
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}-$(APPVEYOR_REPO_COMMIT)"
before_build:
  - ps: nuget restore
build:
  project: Tabster.sln
after_build:
  - ps: >-
      .\Deploy\prepare_native_plugins.ps1
  - ps: >-
      .\Deploy\Installer\nsis.ps1
  - $env:sign_tool sign /f "C:\projects\tabster\deploy\tabster.pfx" /p $env:cert_pass /t http://timestamp.comodoca.com/authenticode ".\Deploy\Installer\Tabster {version} Setup.exe"
  - ps: >-
      .\Deploy\Portable\portable.ps1
artifacts:
  - path: "Tabster*Setup.exe" # use wildcards otherwise 'Tabster' subdirectory will be zipped as well
    name: installer
  - path: "Tabster*Portable.exe"
    name: portable